### PR TITLE
1. add basic hexagonal architecture bootstrap

### PR DESCRIPTION
**Pull request by mukezhz**

### CODE REVIEW

**Comment by mukezhz** [comment]
@SushantBabu97 review this

**Comment by Bibekdhkl** [comment]
@mukezhz Can we preview the stuffs here?

**Comment by mukezhz** [comment]
@Bibekdhkl what should I preview?

**Comment by Bibekdhkl** [comment]
I mean like frontend is their some way we can see what has happened till now hehe, a stupid question:D

**Comment by mukezhz** [comment]
@Bibekdhkl waiting for someone to start

**Comment by Bibekdhkl** [comment]
Yo merge garna ki review garna lai  @mukezhz  dai?

**Comment by mukezhz** [comment]
@Bibekdhkl review garera merge garna lai

**Comment by mukezhz** [comment]
1st ma 1 review gara ani 2 ... tesko lai ho numbering chai

**Comment by Bibekdhkl** [comment]
@mukezhz   Reviewer Official nosk matra dekhako xa so k, ma sanga pheri tyo nosk ko id login nai bhayena sad:( image

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Review by SushantBabu97 — APPROVED** [review]

**Pull request merged**
